compilers:
- compiler:
    spec: cce@=15.0.1
    paths:
      cc: /opt/cray/pe/craype/2.7.20/bin/cc
      cxx: /opt/cray/pe/craype/2.7.20/bin/CC
      f77: /opt/cray/pe/craype/2.7.20/bin/ftn
      fc: /opt/cray/pe/craype/2.7.20/bin/ftn
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@=15.0.1
    paths:
      cc: /opt/cray/pe/cce/15.0.1/cce-clang/x86_64/bin/clang
      cxx: /opt/cray/pe/cce/15.0.1/cce-clang/x86_64/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=8.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: nvhpc@=23.5
    paths:
      cc: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvc
      cxx: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvc++
      f77: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvfortran
      fc: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: rocmcc@=5.4.1
    paths:
      cc: /opt/rocm-5.4.1/bin/amdclang
      cxx: /opt/rocm-5.4.1/bin/amdclang++
      f77: /opt/rocm-5.4.1/bin/amdflang
      fc: /opt/rocm-5.4.1/bin/amdflang
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@amd@15.0.0
    paths:
      cc: /opt/rocm/llvm/bin/clang
      cxx: /opt/rocm/llvm/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=12.2.0
    paths:
      cc: /opt/cray/pe/gcc/12.2.0/bin/gcc
      cxx: /opt/cray/pe/gcc/12.2.0/bin/g++
      f77: /opt/cray/pe/gcc/12.2.0/bin/gfortran
      fc: /opt/cray/pe/gcc/12.2.0/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@=2023.2.0
    paths:
      cc: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/icx
      cxx: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/dpcpp
      f77: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/ifx
      fc: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/ifx
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@=2021.10.0
    paths:
      cc: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/intel64/icc
      cxx: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/intel64/icpc
      f77: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/intel64/ifort
      fc: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@=2023.2.0
    paths:
      cc: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/icx
      cxx: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/icpx
      f77: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/ifx
      fc: /lustre/software/x86/tools/oneapi-2023.2.0/compiler/2023.2.0/linux/bin/ifx
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules:
    - gcc@12.2.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: nvhpc@=23.5
    paths:
      cc: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvc
      cxx: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvc++
      f77: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvfortran
      fc: /opt/nvidia/hpc_sdk/Linux_x86_64/2023/compilers/bin/nvfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []