packages:
  cuda:
    externals:
    - spec: cuda@12.1
      prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/23.5/cuda/12.1/
  hip:
    externals:
    - spec: hip@5.4
      prefix: /opt/rocm-5.4.1/hip
      extra_attributes:
        compilers:
          c: /opt/rocm-5.4.1/llvm/bin/clang++
          c++: /opt/rocm-5.4.1/llvm/bin/clang++
          hip: /opt/rocm-5.4.1/hip/bin/hipcc
    buildable: false
  hsa-rocr-dev:
    externals:
    - spec: hsa-rocr-dev@5.4.1
      prefix: /opt/rocm-5.4.1
      extra_attributes:
        compilers:
          c: /opt/rocm-5.4.1/llvm/bin/clang++
          cxx: /opt/rocm-5.4.1/llvm/bin/clang++
    buildable: false
  llvm-amdgpu:
    externals:
    - spec: llvm-amdgpu@5.4.1
      prefix: /opt/rocm-5.4.1/llvm
      extra_attributes:
        compilers:
          c: /opt/rocm-5.4.1/llvm/bin/clang++
          cxx: /opt/rocm-5.4.1/llvm/bin/clang++
    buildable: false
  rocm-opencl:
    externals:
    - spec: rocm-opencl@5.4.1
      prefix: /opt/rocm-5.4.1/opencl
      extra_attributes:
        compilers:
          c: /opt/rocm-5.4.1/llvm/bin/clang++
          cxx: /opt/rocm-5.4.1/llvm/bin/clang++
    buildable: false
  rocthrust:
    externals:
    - spec: rocthrust@2.17.0
      prefix: /opt/rocm-5.4.1/rocthrust/include/thrust/
  rocprim:
    externals:
    - spec: rocprim@5.4.0
      prefix: /opt/rocm-5.4.1/rocprim/include/rocprim/